Servers = 10
Simulation = "LeavesHTML"
BF = 2
Hosts = 7
Rounds = 10
RunWait = "24h"
Suite = "Ed25519"

Webpage
"https://cdn.rawgit.com/dedis/student_18_decenar/simulation/simulation/test_input/leaves/4096.html"
