Simulation = "LeavesHTML"
Servers = 2
Depth = 1
Hosts = 16
Rounds = 5
#RunWait = "24h"
Suite = "Ed25519"
Delay = 100

Webpage
"https://cdn.rawgit.com/dedis/student_18_decenar/simulation/simulation/test_input/leaves/64.html"
"https://cdn.rawgit.com/dedis/student_18_decenar/simulation/simulation/test_input/leaves/128.html"
"https://cdn.rawgit.com/dedis/student_18_decenar/simulation/simulation/test_input/leaves/256.html"
"https://cdn.rawgit.com/dedis/student_18_decenar/simulation/simulation/test_input/leaves/512.html"
"https://cdn.rawgit.com/dedis/student_18_decenar/simulation/simulation/test_input/leaves/1024.html"
"https://cdn.rawgit.com/dedis/student_18_decenar/simulation/simulation/test_input/leaves/2048.html"
