Simulation = "RealLife"
Servers = 2
Depth = 1
Hosts = 16
Rounds = 5
#RunWait = "24h"
Suite = "Ed25519"
Delay = 100

Webpage
"http://www.bbc.com/news/world-europe-44313905"
"http://www.20min.ch/ro/"
"http://www.20min.ch/ro/news/monde/story/L-UE-repliquera-de-fa-on--unie--aux-sanctions-US-27701771"
"https://www.internazionale.it/bloc-notes/2018/05/31/governo-italiano-fantasma-stampa-straniera"
"https://www.theguardian.com/cities/2018/may/09/fuck-off-google-the-berlin-neighbourhood-fighting-off-a-tech-giant-kreuzberg"
"https://twitter.com/ignaziocassis"
"http://tass.com/politics/1007602"
